version: 2.1

jobs:
  test:
      docker:
        - image: circleci/node:14-buster
      steps:
        - checkout

        # Cache, see: https://circleci.com/docs/2.0/language-javascript/#sample-configuration
        - restore_cache:
            key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

        - run:
            command: |
              yarn
              yarn test

        - save_cache:
            key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
              - ./node_modules
  deploy:
    docker:
        - image: circleci/node:14-buster
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          command: |
            # Trigger a CircleCI build of datenanfragen/website. We are starting this first, so it can run in parallel
            # with the Typesense deploy.
            curl --fail -X POST https://circleci.com/api/v1.1/project/github/datenanfragen/website/build -H "Circle-Token: ${PERSONAL_CIRCLE_TOKEN}"

            # Do the actual Typesense deploy.
            yarn
            yarn deploy

      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  review:
    docker:
        - image: circleci/node:14-buster
    steps:
        - checkout
        - run: sudo apt update
        - run: sudo apt install golang
        # https://github.com/reviewdog/reviewdog#circle-ci
        - run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin     

        # Cache, see: https://circleci.com/docs/2.0/language-javascript/#sample-configuration
        - restore_cache:
            key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - run: yarn ts-node src/test-records.ts --autofix
        # https://github.com/reviewdog/reviewdog#diff
        - run: F=${mktemp} 
        - run: echo "oh no: I${F}I"
        - run: git diff > "${F}"
        - run: git stash -u
        - run: git stash drop
        - run: ./bin/reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review < "${F}"


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - review
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: /^master$/
